title: "[Discussion] "
labels: ["discussion"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for starting a discussion! Please provide as much detail as possible.

  - type: textarea
    id: topic
    attributes:
      label: Topic
      description: What would you like to discuss?
      placeholder: Describe your topic here...
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Any additional information or context?
      placeholder: Add any relevant information here...

  - type: checkboxes
    id: category
    attributes:
      label: Category
      options:
        - label: Feature Request
        - label: Architecture Discussion
        - label: Performance
        - label: Security
        - label: Use Case
        - label: Other
