title: "[Showcase] "
labels: ["showcase"]
body:
  - type: markdown
    attributes:
      value: |
        Show us what you've built with the Drone Swarm System! 🎉

  - type: input
    id: project-name
    attributes:
      label: Project Name
      description: What's your project called?
      placeholder: My Awesome Drone Project
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Tell us about your project
      placeholder: What does it do? What problem does it solve?
    validations:
      required: true

  - type: textarea
    id: implementation
    attributes:
      label: Implementation Details
      description: How did you use the drone swarm system?
      placeholder: Which modules did you use? Any customizations?

  - type: input
    id: link
    attributes:
      label: Project Link
      description: Link to your project (GitHub, website, video, etc.)
      placeholder: https://github.com/username/project

  - type: textarea
    id: media
    attributes:
      label: Screenshots/Videos
      description: Add any images or videos
      placeholder: Drag and drop or paste images here...

  - type: checkboxes
    id: features
    attributes:
      label: Features Used
      options:
        - label: Mesh Networking
        - label: Consensus (Raft)
        - label: Federated Learning
        - label: Swarm Intelligence (PSO/ACO/GWO)
        - label: Formation Control
        - label: Cryptography
